name: Deploy Storybook to GitHub Pages

on:
  push:
    branches:
      - master # 每次 push 到 master 时触发部署

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Build Storybook
        run: pnpm --filter @repo/ui build-storybook -o storybook-static
        working-directory: packages/ui

      - name: Add .nojekyll to bypass Jekyll on GitHub Pages
        run: touch packages/ui/storybook-static/.nojekyll # 添加 （跳过）.nojekyll 文件 GitHub Pages 默认会用 Jekyll 去构建你的仓库，但你的仓库不是 Jekyll 项目（它是前端组件库 Monorepo）

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}   
          publish_dir: packages/ui/storybook-static